spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 0d36d0441db1e90b311ad2d63722e743
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname